# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json tsconfig.json codegen.ts ./
COPY graphql ./graphql

# Copy source files
COPY index.ts ./

RUN npm ci --ignore-scripts && \
    npm run codegen && \
    npm run build

# Copy any remaining files (if required)
# (In this repo, source and graphql are already copied)

# Launch the MCP server over stdio
CMD ["node", "dist/index.js"]
